format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$line_break\
$time\
$character"""

[git_metrics]
disabled = false

[time]
disabled = false
format = "[$time](bright-black)"
